language: node_js
node_js:
  - "node"
env:
  - BROWSERS=PhantomJS
  - BROWSERS=jsdom
  - BROWSERS=Firefox
  - BROWSERS=Chrome
  - BROWSERS=Opera
  - BROWSERS=Safari
  - BROWSERS=IE11
  - BROWSERS=IE10
  - BROWSERS=IE9
  - BROWSERS=IE8
matrix:
  allow_failures:
    - env: BROWSERS=IE8
before_script: make lint
script: make test-ci
