language: node_js
node_js:
  - "node"
env:
  - BROWSERS=PhantomJS
  - BROWSERS=jsdom
  - BROWSERS=Firefox
  - BROWSERS=Chrome
  - BROWSERS=Safari
  - BROWSERS=Edge18
  - BROWSERS=Edge17
  - BROWSERS=Edge16
  - BROWSERS=Edge15
  - BROWSERS=Edge14
  - BROWSERS=Edge13
  - BROWSERS=IE11
  - BROWSERS=IE10
  - BROWSERS=IE9
  - BROWSERS=IE8
matrix:
  allow_failures:
    - env: BROWSERS=IE8
cache:
  directories:
    - node_modules
stages:
  - ensure built
  - lint
  - test
jobs:
  include:
    - stage: ensure built
      script: make build && [ -z "$(git status -s dist/)" ]
    - stage: lint
      script: make lint
script: env TEST_AGAINST_BUILD=1 make test-ci
