language: node_js
node_js:
  - "node"
env:
  - BROWSERS=PhantomJS,jsdom,Firefox,Chrome,Opera,Safari,IE11,IE10,IE9
  - BROWSERS=IE8
matrix:
  allow_failures:
    - env: BROWSERS=IE8
before_script: make lint
script: make test-ci
